@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NjM4NTBhMS03NWJhLTRmMDktYmY3ZS1jMGNhNjJiMGVhMTgiLCJwaG9uZSI6Ijg0Mzc2OTYzNjUzIiwiaWF0IjoxNzQ0ODc5OTU5LCJleHAiOjE3NDQ5NjYzNTl9.7JH-0QxztotOfobnrrM0ubBpDgACFW7u5bZLRj33a6c
@group_id = 64514eaf-b51d-4a00-a2e8-44586fc23b0c
@user_id = 346f45cb-af42-4f2d-9b15-eb7aa29e4b86
@member_id = 123

GET http://localhost:3000/api/users/recent-contacts
Authorization: Bearer {{authToken}}

### Create group
POST http://localhost:3000/api/groups
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "members": [
    "463850a1-75ba-4f09-bf7e-c0ca62b0ea18",
    "b6b1463f-ec88-4232-bcca-dc4e294cefe4"
  ],
  "createdBy": "463850a1-75ba-4f09-bf7e-c0ca62b0ea18",
  "name": "Nhóm gì ai biết"
}

### Update group info
PUT http://localhost:3000/api/groups/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Giờ là biết rồi",
  "avatar": "https://users-zalolite.s3.ap-southeast-1.amazonaws.com/avatars/84112233445_1744861231732.jpg"
}

### Get group by ID
GET http://localhost:3000/api/groups/{{group_id}}
Authorization: Bearer {{authToken}}

### Delete group
DELETE http://localhost:3000/api/groups/{{group_id}}
Authorization: Bearer {{authToken}}

### Add member
POST http://localhost:3000/api/groups/{{group_id}}/members
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "346f45cb-af42-4f2d-9b15-eb7aa29e4b86",
  "role": "MEMBER"
}

### Get members
GET http://localhost:3000/api/groups/{{group_id}}/members
Authorization: Bearer {{authToken}}

### Update member role
PUT http://localhost:3000/api/groups/{{group_id}}/members/{{user_id}}/role
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "MEMBER"
}

### Remove member
DELETE http://localhost:3000/api/groups/{{group_id}}/members/{{user_id}}
Authorization: Bearer {{authToken}}

### Get user's groups
GET http://localhost:3000/api/users/463850a1-75ba-4f09-bf7e-c0ca62b0ea18/groups
Authorization: Bearer {{authToken}}

### Update last read
PUT http://localhost:3000/api/groups/{{group_id}}/members/{{user_id}}/last-read
Authorization: Bearer {{authToken}} 