### Create a new group

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaG9uZSI6Ijg0Mzc2OTYzNjUzIiwiaWF0IjoxNzQ0ODYxODgyLCJleHAiOjE3NDQ5NDgyODJ9.fmRDgu_TJtmJ_mPtf3yPvH5zqCO5CEu8Yj_BMyL32hM
@group_id = 748d4a9b-5654-4579-b688-8c6de7850829
@user_id = 84376963653
@member_id = 123

POST http://localhost:3000/api/groups
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Test Group",
  "description": "This is a test group",
  "createdBy": "84376963653"
}

### Get group by ID
GET http://localhost:3000/api/groups/{{group_id}}
Authorization: Bearer {{authToken}}

### Update group
PUT http://localhost:3000/api/groups/{{group_id}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Updated Group Name",
  "description": "Updated group description",
  "avatar": "https://users-zalolite.s3.ap-southeast-1.amazonaws.com/avatars/84112233445_1744861231732.jpg"
}

### Delete group (soft delete)
DELETE http://localhost:3000/api/groups/{{group_id}}
Authorization: Bearer {{authToken}}

### Add member to group
### Add member
POST http://localhost:3000/api/groups/123/members/84123456789
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "MEMBER",
  "nickname": "New Member"
}

### Get group members
GET http://localhost:3000/api/groups/{{group_id}}/members
Authorization: Bearer {{authToken}}

### Update member role
PUT http://localhost:3000/api/groups/{{group_id}}/members/{{member_id}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "MODERATOR",
  "nickname": "Updated Nickname"
}

### Remove member from group
DELETE http://localhost:3000/api/groups/{{group_id}}/members/{{member_id}}
Authorization: Bearer {{authToken}}

### Get user's groups
GET http://localhost:3000/api/users/{{user_id}}/groups
Authorization: Bearer {{authToken}}

### Update last read timestamp
PUT http://localhost:3000/api/groups/{{group_id}}/members/{{member_id}}/last-read
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "timestamp": "2024-04-16T12:00:00Z"
} 